In [2]:
import numpy as np

# DataTypes & Attributes

In [3]:
# Numpy's main datatypes is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2.30,7],
               [4,5.7,9]])

a3 = np.array([[[1,2,4],[3,5,6],[7,8,9]],[[10,11,12],[13,15,14],[16,17,18]]])

In [6]:
a2

array([[1. , 2.3, 7. ],
       [4. , 5.7, 9. ]])

In [7]:
a3

array([[[ 1,  2,  4],
        [ 3,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 15, 14],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [12]:
a1 , a2 , a3

(array([1, 2, 3]),
 array([[1. , 2.3, 7. ],
        [4. , 5.7, 9. ]]),
 array([[[ 1,  2,  4],
         [ 3,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 15, 14],
         [16, 17, 18]]]))

In [13]:
a1.dtype , a2.dtype , a3.dtype 

(dtype('int64'), dtype('float64'), dtype('int64'))

In [14]:
a1.size , a2.size, a3.size

(3, 6, 18)

In [15]:
type(a1) , type(a2) , type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

# Create a DataFrame from a Numpy array

In [16]:
# Create a DataFrame from a Numpy array

import pandas as pd

df = pd.DataFrame(a2)

In [17]:
df

0    1    2
0  1.0  2.3  7.0
1  4.0  5.7  9.0

# 2. Creating Arrays

In [18]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [19]:
sample_array.dtype

dtype('int64')

In [20]:
ones = np.ones((2,3),int)

In [21]:
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [22]:
ones.dtype

dtype('int64')

In [23]:
type(ones)

numpy.ndarray

In [24]:
zeros = np.zeros((2,4))

In [25]:
zeros.dtype

dtype('float64')

In [26]:
type(zeros)

numpy.ndarray

In [27]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
range_array = np.arange(0,12)
range_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
range_array = np.arange(0,12,2)
range_array

array([ 0,  2,  4,  6,  8, 10])

In [30]:
random_array = np.random.randint(0,10,size=(2,5))

In [31]:
random_array

array([[6, 0, 3, 7, 5],
       [0, 6, 9, 8, 2]], dtype=int32)

In [32]:
random_array.size , random_array.shape

(10, (2, 5))

In [33]:
random_array2 = np.random.random((4,4))
random_array2

array([[0.72178145, 0.58286496, 0.72516586, 0.32232792],
       [0.77642274, 0.72054048, 0.87334811, 0.08790981],
       [0.65408583, 0.61639333, 0.65137503, 0.70675809],
       [0.97611339, 0.52348866, 0.65483857, 0.26346404]])

In [34]:
random_array2.shape

(4, 4)

In [35]:
random_array3 = np.random.rand(4,3)
random_array3

array([[0.50249022, 0.42432598, 0.05743225],
       [0.93333825, 0.55595219, 0.50241084],
       [0.67590859, 0.41773592, 0.41576147],
       [0.84421043, 0.57230452, 0.31574372]])

In [36]:
# Pseudo-random numbers
np.random.seed()

In [37]:
n = np.random.seed()

In [38]:
n

In [39]:
np.random.seed(0)
random_array4 = np.random.randint(10,size=(4,4))
random_array4

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6],
       [8, 8, 1, 6]], dtype=int32)

In [40]:
random_array4.shape

(4, 4)

In [41]:
np.random.seed(7)
random_array5 = np.random.random((4,4))
random_array5

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518],
       [0.97798951, 0.53849587, 0.50112046, 0.07205113],
       [0.26843898, 0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 , 0.90959353]])

In [42]:
random_array5

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518],
       [0.97798951, 0.53849587, 0.50112046, 0.07205113],
       [0.26843898, 0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 , 0.90959353]])

# 3 Viewing Arrays and Matrix

In [43]:
np.unique(random_array4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [44]:
a3[0]

array([[1, 2, 4],
       [3, 5, 6],
       [7, 8, 9]])

In [45]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 3,  5]],

       [[10, 11],
        [13, 15]]])

In [46]:
a4 = np.random.randint(20,size=(2,3,4,5))

In [47]:
a4

array([[[[12,  5, 16,  0,  2],
         [ 9, 14,  6,  4, 14],
         [ 9,  3,  3,  8, 19],
         [16,  1,  0, 16, 12]],

        [[ 7, 10,  9,  3,  0],
         [ 7,  0,  4,  3,  1],
         [ 3,  1, 19,  4, 19],
         [ 1,  5,  9, 17,  2]],

        [[19, 18, 18,  3, 11],
         [15, 16, 12, 11,  9],
         [ 9, 12,  3, 14, 14],
         [15,  3, 16,  4, 11]]],


       [[[ 8, 11, 15, 13, 18],
         [ 7,  3, 12, 12, 15],
         [ 8,  6,  6, 12,  7],
         [17, 10, 15,  5,  4]],

        [[ 9,  9,  0,  2, 12],
         [ 6,  8,  2, 10, 14],
         [17,  6, 10, 17,  5],
         [15, 17, 12,  9,  8]],

        [[15,  5,  9,  4, 12],
         [ 9, 11,  6,  1, 11],
         [19, 12, 12, 13,  4],
         [ 7,  9,  6, 15, 11]]]], dtype=int32)

In [48]:
a4.ndim , a4.size , a4.shape

(4, 120, (2, 3, 4, 5))

In [49]:
type(a4)

numpy.ndarray

In [50]:
a4[: ,:, :, :4]

array([[[[12,  5, 16,  0],
         [ 9, 14,  6,  4],
         [ 9,  3,  3,  8],
         [16,  1,  0, 16]],

        [[ 7, 10,  9,  3],
         [ 7,  0,  4,  3],
         [ 3,  1, 19,  4],
         [ 1,  5,  9, 17]],

        [[19, 18, 18,  3],
         [15, 16, 12, 11],
         [ 9, 12,  3, 14],
         [15,  3, 16,  4]]],


       [[[ 8, 11, 15, 13],
         [ 7,  3, 12, 12],
         [ 8,  6,  6, 12],
         [17, 10, 15,  5]],

        [[ 9,  9,  0,  2],
         [ 6,  8,  2, 10],
         [17,  6, 10, 17],
         [15, 17, 12,  9]],

        [[15,  5,  9,  4],
         [ 9, 11,  6,  1],
         [19, 12, 12, 13],
         [ 7,  9,  6, 15]]]], dtype=int32)

# 4 Manipulating & Comparing Arrays

Arithmetic

In [51]:
a1

array([1, 2, 3])

In [52]:
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [53]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [54]:
ones = np.ones(3,int)
ones

array([1, 1, 1])

In [55]:
a1 + ones

array([2, 3, 4])

In [56]:
a1 -ones

array([0, 1, 2])

In [57]:
a1 * ones

array([1, 2, 3])

In [58]:
a2 

array([[1. , 2.3, 7. ],
       [4. , 5.7, 9. ]])

In [59]:
a2 * a1

array([[ 1. ,  4.6, 21. ],
       [ 4. , 11.4, 27. ]])

In [60]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [61]:
# How can you reshape a2 to be compatible with a3?
# Search : "How to reshape numpy array"



In [62]:
a1/ones

array([1., 2., 3.])

In [63]:
a2/a1

array([[1.        , 1.15      , 2.33333333],
       [4.        , 2.85      , 3.        ]])

In [64]:
# Floor division removes the decimals (rounds down)

a2 // a1

array([[1., 1., 2.],
       [4., 2., 3.]])

In [65]:
a2** a1

array([[  1.  ,   5.29, 343.  ],
       [  4.  ,  32.49, 729.  ]])

In [66]:
np.square(a2)

array([[ 1.  ,  5.29, 49.  ],
       [16.  , 32.49, 81.  ]])

In [67]:
np.add(a1,ones)

array([2, 3, 4])

In [68]:
a1 + ones

array([2, 3, 4])

In [69]:
a1 % 2

array([1, 0, 1])

In [70]:
a1 / 2

array([0.5, 1. , 1.5])

In [71]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [72]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation 

Aggregation = performing the same operation on a number of things

In [ ]:
lists = [1,2,3]
type(list)

type

In [73]:
sum(lists)

6

In [74]:
type(a1)

numpy.ndarray

In [75]:
sum(a1)

np.int64(6)

In [76]:
np.sum(a1)

np.int64(6)

Use Python's methods (`sum()`) on Python datatypes ans use Numpy's methods on Numpy arrays (`np.sum()`).

In [77]:
# Creative a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [ ]:
massive_array[:10]

array([0.60777075, 0.82845319, 0.94180927, 0.12814785, 0.23043067,
       0.6591584 , 0.13247399, 0.22407864, 0.57486259, 0.16952372])

In [79]:
%timeit sum(massive_array)  # Python's sum()
%timeit np.sum(massive_array) # NumPy's sum()

5.49 ms ± 197 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
32.8 μs ± 118 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [80]:
a2

array([[1. , 2.3, 7. ],
       [4. , 5.7, 9. ]])

In [81]:
a2.mean()

np.float64(4.833333333333333)

In [82]:
np.max(a2)

np.float64(9.0)

In [83]:
np.min(a2)

np.float64(1.0)

In [ ]:
# Standard deviation =  a measure of how spread out a group of number is from the mean
# equal to variance of sqrt square root

a2.std()

np.float64(2.726821511495675)

In [ ]:
# variance = measure of the average degree to which each number is different
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

np.float64(7.435555555555556)

In [86]:
np.sqrt(np.var(a2))

np.float64(2.726821511495675)