In [1]:
import numpy as np

# DataTypes & Attributes

In [3]:
# Numpy's main datatypes is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2.30,7],
               [4,5.7,9]])

a3 = np.array([[[1,2,4],[3,5,6],[7,8,9]],[[10,11,12],[13,15,14],[16,17,18]]])

In [6]:
a2

array([[1. , 2.3, 7. ],
       [4. , 5.7, 9. ]])

In [7]:
a3

array([[[ 1,  2,  4],
        [ 3,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 15, 14],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [12]:
a1 , a2 , a3

(array([1, 2, 3]),
 array([[1. , 2.3, 7. ],
        [4. , 5.7, 9. ]]),
 array([[[ 1,  2,  4],
         [ 3,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 15, 14],
         [16, 17, 18]]]))

In [13]:
a1.dtype , a2.dtype , a3.dtype 

(dtype('int64'), dtype('float64'), dtype('int64'))

In [14]:
a1.size , a2.size, a3.size

(3, 6, 18)

In [15]:
type(a1) , type(a2) , type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

# Create a DataFrame from a Numpy array

In [16]:
# Create a DataFrame from a Numpy array

import pandas as pd

df = pd.DataFrame(a2)

In [17]:
df

0    1    2
0  1.0  2.3  7.0
1  4.0  5.7  9.0

# 2. Creating Arrays

In [18]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [19]:
sample_array.dtype

dtype('int64')

In [20]:
ones = np.ones((2,3),int)

In [21]:
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [22]:
ones.dtype

dtype('int64')

In [23]:
type(ones)

numpy.ndarray

In [24]:
zeros = np.zeros((2,4))

In [25]:
zeros.dtype

dtype('float64')

In [27]:
type(zeros)

numpy.ndarray

In [28]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
range_array = np.arange(0,12)
range_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
range_array = np.arange(0,12,2)
range_array

array([ 0,  2,  4,  6,  8, 10])

In [31]:
random_array = np.random.randint(0,10,size=(2,5))

In [32]:
random_array

array([[2, 5, 3, 0, 4],
       [7, 1, 2, 2, 9]], dtype=int32)

In [33]:
random_array.size , random_array.shape

(10, (2, 5))

In [34]:
random_array2 = np.random.random((4,4))
random_array2

array([[0.56792745, 0.44883144, 0.57412094, 0.15117526],
       [0.78990014, 0.48989222, 0.41999327, 0.18690985],
       [0.55881371, 0.0378778 , 0.41180458, 0.23658487],
       [0.42112735, 0.99874337, 0.71290617, 0.39083359]])

In [35]:
random_array2.shape

(4, 4)

In [36]:
random_array3 = np.random.rand(4,3)
random_array3

array([[0.82024988, 0.81290277, 0.21276007],
       [0.58693475, 0.01417719, 0.99749689],
       [0.09961053, 0.36877438, 0.92612047],
       [0.32862902, 0.93512437, 0.92334689]])

In [ ]:
# Pseudo-random numbers
np.random.seed()

In [38]:
n = np.random.seed()

In [39]:
n

In [41]:
np.random.seed(0)
random_array4 = np.random.randint(10,size=(4,4))
random_array4

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6],
       [8, 8, 1, 6]], dtype=int32)

In [42]:
random_array4.shape

(4, 4)

In [43]:
np.random.seed(7)
random_array5 = np.random.random((4,4))
random_array5

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518],
       [0.97798951, 0.53849587, 0.50112046, 0.07205113],
       [0.26843898, 0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 , 0.90959353]])

In [44]:
random_array5

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518],
       [0.97798951, 0.53849587, 0.50112046, 0.07205113],
       [0.26843898, 0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 , 0.90959353]])

# 3 Viewing Arrays and Matrix

In [45]:
np.unique(random_array4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [46]:
a3[0]

array([[1, 2, 4],
       [3, 5, 6],
       [7, 8, 9]])

In [47]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 3,  5]],

       [[10, 11],
        [13, 15]]])

In [48]:
a4 = np.random.randint(20,size=(2,3,4,5))

In [49]:
a4

array([[[[12,  5, 16,  0,  2],
         [ 9, 14,  6,  4, 14],
         [ 9,  3,  3,  8, 19],
         [16,  1,  0, 16, 12]],

        [[ 7, 10,  9,  3,  0],
         [ 7,  0,  4,  3,  1],
         [ 3,  1, 19,  4, 19],
         [ 1,  5,  9, 17,  2]],

        [[19, 18, 18,  3, 11],
         [15, 16, 12, 11,  9],
         [ 9, 12,  3, 14, 14],
         [15,  3, 16,  4, 11]]],


       [[[ 8, 11, 15, 13, 18],
         [ 7,  3, 12, 12, 15],
         [ 8,  6,  6, 12,  7],
         [17, 10, 15,  5,  4]],

        [[ 9,  9,  0,  2, 12],
         [ 6,  8,  2, 10, 14],
         [17,  6, 10, 17,  5],
         [15, 17, 12,  9,  8]],

        [[15,  5,  9,  4, 12],
         [ 9, 11,  6,  1, 11],
         [19, 12, 12, 13,  4],
         [ 7,  9,  6, 15, 11]]]], dtype=int32)

In [51]:
a4.ndim , a4.size , a4.shape

(4, 120, (2, 3, 4, 5))

In [52]:
type(a4)

numpy.ndarray

In [54]:
a4[: ,:, :, :4]

array([[[[12,  5, 16,  0],
         [ 9, 14,  6,  4],
         [ 9,  3,  3,  8],
         [16,  1,  0, 16]],

        [[ 7, 10,  9,  3],
         [ 7,  0,  4,  3],
         [ 3,  1, 19,  4],
         [ 1,  5,  9, 17]],

        [[19, 18, 18,  3],
         [15, 16, 12, 11],
         [ 9, 12,  3, 14],
         [15,  3, 16,  4]]],


       [[[ 8, 11, 15, 13],
         [ 7,  3, 12, 12],
         [ 8,  6,  6, 12],
         [17, 10, 15,  5]],

        [[ 9,  9,  0,  2],
         [ 6,  8,  2, 10],
         [17,  6, 10, 17],
         [15, 17, 12,  9]],

        [[15,  5,  9,  4],
         [ 9, 11,  6,  1],
         [19, 12, 12, 13],
         [ 7,  9,  6, 15]]]], dtype=int32)

# 4 Manipulating & Comparing Arrays

Arithmetic

In [55]:
a1

array([1, 2, 3])

In [56]:
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [57]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [58]:
ones = np.ones(3,int)
ones

array([1, 1, 1])

In [59]:
a1 + ones

array([2, 3, 4])

In [60]:
a1 -ones

array([0, 1, 2])

In [61]:
a1 * ones

array([1, 2, 3])

In [62]:
a2 

array([[1. , 2.3, 7. ],
       [4. , 5.7, 9. ]])

In [63]:
a2 * a1

array([[ 1. ,  4.6, 21. ],
       [ 4. , 11.4, 27. ]])

In [64]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
# How can you reshape a2 to be compatible with a3?
# Search : "How to reshape numpy array"



In [65]:
a1/ones

array([1., 2., 3.])

In [66]:
a2/a1

array([[1.        , 1.15      , 2.33333333],
       [4.        , 2.85      , 3.        ]])

In [67]:
# Floor division removes the decimals (rounds down)

a2 // a1

array([[1., 1., 2.],
       [4., 2., 3.]])

In [68]:
a2** a1

array([[  1.  ,   5.29, 343.  ],
       [  4.  ,  32.49, 729.  ]])

In [69]:
np.square(a2)

array([[ 1.  ,  5.29, 49.  ],
       [16.  , 32.49, 81.  ]])

In [70]:
np.add(a1,ones)

array([2, 3, 4])

In [71]:
a1 + ones

array([2, 3, 4])

In [72]:
a1 % 2

array([1, 0, 1])

In [73]:
a1 / 2

array([0.5, 1. , 1.5])

In [74]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [75]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])